/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
	export interface GlobalComponents {
		Accordion: typeof import('primevue/accordion')['default']
		AccordionContent: typeof import('primevue/accordioncontent')['default']
		AccordionHeader: typeof import('primevue/accordionheader')['default']
		AccordionPanel: typeof import('primevue/accordionpanel')['default']
		App: typeof import('./src/client/App.vue')['default']
		Await: typeof import('./src/client/components/Await.vue')['default']
		Button: typeof import('primevue/button')['default']
		EntryViewer: typeof import('./src/client/components/EntryViewer.vue')['default']
		ErrorView: typeof import('./src/client/components/ErrorView.vue')['default']
		InputNumber: typeof import('primevue/inputnumber')['default']
		InputSwitch: typeof import('primevue/inputswitch')['default']
		List: typeof import('./src/client/views/List.vue')['default']
		Menubar: typeof import('primevue/menubar')['default']
		Module: typeof import('./src/client/views/Module.vue')['default']
		ModuleViewer: typeof import('./src/client/views/ModuleViewer.vue')['default']
		Panel: typeof import('primevue/panel')['default']
		Parameter: typeof import('./src/client/components/Parameter.vue')['default']
		Parameters: typeof import('./src/client/components/Parameters.vue')['default']
		Preview: typeof import('./src/client/views/Preview.vue')['default']
		ProgressSpinner: typeof import('primevue/progressspinner')['default']
		RouterLink: typeof import('vue-router')['RouterLink']
		RouterView: typeof import('vue-router')['RouterView']
		Select: typeof import('primevue/select')['default']
		Slider: typeof import('primevue/slider')['default']
		SlidParameter: typeof import('./src/client/components/SlidParameter.vue')['default']
		Spinner: typeof import('./src/client/components/Spinner.vue')['default']
		Splitter: typeof import('primevue/splitter')['default']
		SplitterPanel: typeof import('primevue/splitterpanel')['default']
		Tree: typeof import('primevue/tree')['default']
		Viewer: typeof import('./src/client/components/Viewer.vue')['default']
	}
}
