/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/client/App.vue')['default']
    Await: typeof import('./src/client/components/Await.vue')['default']
    Button: typeof import('primevue/button')['default']
    EntryViewer: typeof import('./src/client/components/EntryViewer.vue')['default']
    ErrorView: typeof import('./src/client/components/ErrorView.vue')['default']
    List: typeof import('./src/client/views/List.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    ModuleViewer: typeof import('./src/client/views/ModuleViewer.vue')['default']
    Parameter: typeof import('./src/client/components/Parameter.vue')['default']
    Parameters: typeof import('./src/client/components/Parameters.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlidParameter: typeof import('./src/client/components/SlidParameter.vue')['default']
    Spinner: typeof import('./src/client/components/Spinner.vue')['default']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    Tree: typeof import('primevue/tree')['default']
    Viewer: typeof import('./src/client/components/Viewer.vue')['default']
  }
}
